### ISSUE TITLE
File words/voornamen.csv missing

### ISSUE THREAD

**Issue by gmloose** [remko/dicewords#2]
Nice piece of work. Thanks.

It seems that the file `words/voornamen.csv` is missing in `master`. 
When running `./db-initialize.rb`, I get the following error:
```
Importing voornamen_score
Traceback (most recent call last):
	3: from ./db-initialize.rb:36:in `<main>'
	2: from ./db-initialize.rb:36:in `each'
	1: from ./db-initialize.rb:39:in `block in <main>'
./db-initialize.rb:39:in `read': No such file or directory @ rb_sysopen - words/nl/voornamen.csv (Errno::ENOENT)
```

**Comment by remko** [comment]
Thanks for letting me know. Added.
